/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Colaborador;
import LogicaNegocio.LogicaColaborador;
import javax.swing.JOptionPane;

/**
 *
 * @author regr9
 */
public class InterfazTomaDatos extends javax.swing.JFrame {

    /**
     * Creates new form InterfazTomaDatos
     */
    public InterfazTomaDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonCalcularSalario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadHorasOridinarias = new javax.swing.JTextField();
        txtHorasExtrasSencillas = new javax.swing.JTextField();
        txtSalarioPorHora = new javax.swing.JTextField();
        txtExtrasHorasDobles = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCalcularSalario.setText("Calcular");
        botonCalcularSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularSalarioActionPerformed(evt);
            }
        });
        jPanel2.add(botonCalcularSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel2.setText("Cantidad de horas ordinarias");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("Horas extras sencillas");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setText("Horas extras dobles");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setText("Salario por hora");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtCantidadHorasOridinarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadHorasOridinariasActionPerformed(evt);
            }
        });
        jPanel2.add(txtCantidadHorasOridinarias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 100, -1));
        jPanel2.add(txtHorasExtrasSencillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, -1));
        jPanel2.add(txtSalarioPorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 100, -1));
        jPanel2.add(txtExtrasHorasDobles, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingrese los datos.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 670, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 880, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularSalarioActionPerformed

        LogicaColaborador objLogicaColaborador = new LogicaColaborador();
        Colaborador objColaborador = new Colaborador();

        objColaborador.setSalarioHora(Double.parseDouble(txtSalarioPorHora.getText()));
        objColaborador.setHorasTrabajadas(Double.parseDouble(txtCantidadHorasOridinarias.getText()));
        objColaborador.setExtrasCorrientes(Double.parseDouble(txtHorasExtrasSencillas.getText()));
        objColaborador.setExtrasDobles(Double.parseDouble(txtExtrasHorasDobles.getText()));

        objLogicaColaborador.calculoHorasExtrasNormales(objColaborador);
        objLogicaColaborador.calculoHorasExtrasDobles(objColaborador);
        objLogicaColaborador.calculoSalarioBase(objColaborador);
        objLogicaColaborador.salarioSinDeducciones();
        objLogicaColaborador.impuestosSobreRenta();
        objLogicaColaborador.semPatrono();
        objLogicaColaborador.ivmPatrono();
        objLogicaColaborador.cajaPatrono();
        objLogicaColaborador.cuotaPopularPatrono();
        objLogicaColaborador.asignacionesFamiliares();
        objLogicaColaborador.imasDeducciones();
        objLogicaColaborador.inaDeducciones();
        objLogicaColaborador.totalOtrasInstituciones();
        objLogicaColaborador.aportePopularPatrono();
        objLogicaColaborador.fondoCapitalizacion();
        objLogicaColaborador.fondoPensiones();
        objLogicaColaborador.deduccionesInsPatrono();
        objLogicaColaborador.totalLptPatrono();
        objLogicaColaborador.totalPatrono();
        objLogicaColaborador.semTrabajador();
        objLogicaColaborador.ivmTrabajador();
        objLogicaColaborador.cajaTrabajador();
        objLogicaColaborador.aportePopularTrabajador();
        objLogicaColaborador.totalLptTrabajador();
        objLogicaColaborador.calculoSalarioNeto();
        objLogicaColaborador.calculoTotalIvm();
        objLogicaColaborador.calculoTotalSem();
        objLogicaColaborador.calculoTotalCaja();
        objLogicaColaborador.calculoTotalLpt();
        objLogicaColaborador.deduccionesCcssColaborador();
        objLogicaColaborador.deduccionesCcss();
        objLogicaColaborador.calculoSalarioNeto();
         
        
        
        
        InterfazPresentacionResultados objInterfazPresentacionResultados = new InterfazPresentacionResultados();
        objInterfazPresentacionResultados.setVisible(true);
        objInterfazPresentacionResultados.setResizable(false);
        objInterfazPresentacionResultados.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_botonCalcularSalarioActionPerformed

    private void txtCantidadHorasOridinariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadHorasOridinariasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadHorasOridinariasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazTomaDatos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazTomaDatos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazTomaDatos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazTomaDatos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazTomaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcularSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCantidadHorasOridinarias;
    private javax.swing.JTextField txtExtrasHorasDobles;
    private javax.swing.JTextField txtHorasExtrasSencillas;
    private javax.swing.JTextField txtSalarioPorHora;
    // End of variables declaration//GEN-END:variables
}
