/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import LogicaNegocio.LogicaEnviarCorreo;
import LogicaNegocio.LogicaPDF;

/**
 *
 * @author regr9
 */
public class InterfazPresentacionResultados extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPresentacionResultados
     */
    public InterfazPresentacionResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtSEM = new javax.swing.JTextField();
        txtIVM = new javax.swing.JTextField();
        txtTotalCCSS = new javax.swing.JTextField();
        txtCuotaPatronalBancoPopular = new javax.swing.JTextField();
        txtAsignacionFamiliares = new javax.swing.JTextField();
        txtIMAS = new javax.swing.JTextField();
        txtINA = new javax.swing.JTextField();
        txtTotalTrabajador = new javax.swing.JTextField();
        txtAportePatronoBancoPopular = new javax.swing.JTextField();
        txtFCL = new javax.swing.JTextField();
        txtTotalPatrono = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtLPT = new javax.swing.JTextField();
        txtAporteTrabajadorBancoPopular = new javax.swing.JTextField();
        txtFondoPensionComplemetaria = new javax.swing.JTextField();
        txtINS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonCargarResultados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Enviar correo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, -1, -1));

        txtSEM.setEditable(false);
        txtSEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSEMActionPerformed(evt);
            }
        });
        jPanel1.add(txtSEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 62, 90, 30));

        txtIVM.setEditable(false);
        txtIVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIVMActionPerformed(evt);
            }
        });
        jPanel1.add(txtIVM, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 92, 90, 30));

        txtTotalCCSS.setEditable(false);
        txtTotalCCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCCSSActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalCCSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 90, 30));

        txtCuotaPatronalBancoPopular.setEditable(false);
        txtCuotaPatronalBancoPopular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuotaPatronalBancoPopularActionPerformed(evt);
            }
        });
        jPanel1.add(txtCuotaPatronalBancoPopular, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 90, 30));

        txtAsignacionFamiliares.setEditable(false);
        jPanel1.add(txtAsignacionFamiliares, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 90, 30));

        txtIMAS.setEditable(false);
        jPanel1.add(txtIMAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 90, 30));

        txtINA.setEditable(false);
        jPanel1.add(txtINA, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 90, 30));

        txtTotalTrabajador.setEditable(false);
        jPanel1.add(txtTotalTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 672, 80, 30));

        txtAportePatronoBancoPopular.setEditable(false);
        jPanel1.add(txtAportePatronoBancoPopular, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 90, 30));

        txtFCL.setEditable(false);
        jPanel1.add(txtFCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 90, 30));

        txtTotalPatrono.setEditable(false);
        jPanel1.add(txtTotalPatrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 672, 80, 30));

        txtTotal.setEditable(false);
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, 80, 30));

        txtLPT.setEditable(false);
        jPanel1.add(txtLPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 90, 30));

        txtAporteTrabajadorBancoPopular.setEditable(false);
        jPanel1.add(txtAporteTrabajadorBancoPopular, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 90, 30));

        txtFondoPensionComplemetaria.setEditable(false);
        jPanel1.add(txtFondoPensionComplemetaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 90, 30));

        txtINS.setEditable(false);
        jPanel1.add(txtINS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 90, 30));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CCSS1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        botonCargarResultados.setText("Cargar Resultados");
        jPanel1.add(botonCargarResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      LogicaEnviarCorreo objLogicaEnviarCorreo = new LogicaEnviarCorreo();
      LogicaPDF objLogicaPDF = new LogicaPDF();
      
      

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSEMActionPerformed
      
    }//GEN-LAST:event_txtSEMActionPerformed

    private void txtIVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIVMActionPerformed
      
    }//GEN-LAST:event_txtIVMActionPerformed

    private void txtTotalCCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCCSSActionPerformed
        
    }//GEN-LAST:event_txtTotalCCSSActionPerformed

    private void txtCuotaPatronalBancoPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotaPatronalBancoPopularActionPerformed
     
    }//GEN-LAST:event_txtCuotaPatronalBancoPopularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPresentacionResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPresentacionResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPresentacionResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPresentacionResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPresentacionResultados().setVisible(true);
            }
        });
        
        
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarResultados;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAportePatronoBancoPopular;
    private javax.swing.JTextField txtAporteTrabajadorBancoPopular;
    private javax.swing.JTextField txtAsignacionFamiliares;
    private javax.swing.JTextField txtCuotaPatronalBancoPopular;
    private javax.swing.JTextField txtFCL;
    private javax.swing.JTextField txtFondoPensionComplemetaria;
    private javax.swing.JTextField txtIMAS;
    private javax.swing.JTextField txtINA;
    private javax.swing.JTextField txtINS;
    private javax.swing.JTextField txtIVM;
    private javax.swing.JTextField txtLPT;
    private javax.swing.JTextField txtSEM;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalCCSS;
    private javax.swing.JTextField txtTotalPatrono;
    private javax.swing.JTextField txtTotalTrabajador;
    // End of variables declaration//GEN-END:variables

  

  
}
